export const TRIPS = [
  {
    id: '1',
    operator: 'Green Line',
    type: 'AC BUS',
    departureTime: '08:00',
    arrivalTime: '02:30',
    originCode: 'DAC',
    originCity: 'Dhaka, BD',
    destinationCode: 'BAR',
    destinationCity: 'Barishal, BD',
    duration: '6h 30m',
    stops: 'Non-stop',
    remainingSeats: 6,
    price: 42,
  },
  {
    id: '2',
    operator: 'Sakura Paribahan',
    type: 'AC BUS',
    departureTime: '09:00',
    arrivalTime: '04:10',
    originCode: 'DAC',
    originCity: 'Dhaka, BD',
    destinationCode: 'BAR',
    destinationCity: 'Barishal, BD',
    duration: '7h 10m',
    stops: 'One-stop',
    remainingSeats: 15,
    price: 40,
  },
  {
    id: '3',
    operator: 'Hanif Paribahan',
    type: 'NON AC BUS',
    departureTime: '07:00',
    arrivalTime: '12:00',
    originCode: 'DAC',
    originCity: 'Dhaka, BD',
    destinationCode: 'BAR',
    destinationCity: 'Barishal, BD',
    duration: '6h 30m',
    stops: 'Non-stop',
    remainingSeats: 20,
    price: 45,
  },
  {
    id: '4',
    operator: 'Shohagh Paribahan',
    type: 'AC BUS',
    departureTime: '08:30',
    arrivalTime: '03:00',
    originCode: 'DAC',
    originCity: 'Dhaka, BD',
    destinationCode: 'BAR',
    destinationCity: 'Barishal, BD',
    duration: '6h 30m',
    stops: 'Non-stop',
    remainingSeats: 12,
    price: 50,
  },
];
